
export enum IGNISIGN_ID_PROOFING_METHOD_PROCESSING_KIND {
  VALID       = "VALID",
  IN_PROGRESS = "IN_PROGRESS",
  ERROR       = "ERROR"
}

export enum IGNISIGN_ID_PROOFING_METHOD_REF {
  VIDEO_ROBOT_QES             = "VIDEO_ROBOT_QES",
  BANK_ACCOUNT_CHECK          = "BANK_ACCOUNT_CHECK",
  E_ID                        = "E_ID",
  RA_NATURAL_QES              = "RA_NATURAL_QES",
  RA_NATURAL_AES              = "RA_NATURAL_AES",
  BIND_ADDITIONAL_AUTH_METHOD = "BIND_ADDITIONAL_AUTH_METHOD",
}
