import { IGNISIGN_ERROR_CODES } from "../_commons/ignisign-errors.public";

export enum IGNISIGN_AUTH_FACTOR {
  KNOWLEDGE   = "KNOWLEDGE",
  POSSESSION  = "POSSESSION",
  INHERENCE   = "INHERENCE"
}

export enum IGNISIGN_AUTH_RESPONSIBILITY {
  IGNISIGN      = "IGNISIGN",
  ORGANIZATION  = "ORGANIZATION"
}

export enum IGNISIGN_SINGLE_AUTH_METHOD_REF {
  IGNISIGN_TOTP                     = "IGNISIGN_TOTP",
  IGNISIGN_PASS_KEY                = "IGNISIGN_PASS_KEY",
  IGNISIGN_SMS_NONCE                = "IGNISIGN_SMS_NONCE",
  IGNISIGN_CALL_NONCE               = "IGNISIGN_CALL_NONCE",
  IGNISIGN_EMAIL_NONCE              = "IGNISIGN_EMAIL_NONCE",
  IGNISIGN_EMAIL_TOKEN              = "IGNISIGN_EMAIL_TOKEN",
  // IGNISIGN_PHONE_POSSESSION         = "IGNISIGN_PHONE_POSSESSION",
 
  IGNISIGN_DAPP_WALLET              = "IGNISIGN_DAPP_WALLET",
  IGNISIGN_PRIVATE_KEY_POSSESSION   = "IGNISIGN_PRIVATE_KEY_POSSESSION",
  IGNISIGN_EID                      = "IGNISIGN_EID",
  
  
  APP_KNOWLEDGE                     = "APP_KNOWLEDGE",
  // APP_INHERENCE                     = "APP_INHERENCE",
  // APP_POSSESSION                    = "APP_POSSESSION",
  // IGNISIGN_PIN                      = "IGNISIGN_PIN",
  // IGNISIGN_PASSWORD                 = "IGNISIGN_PASSWORD",
  // IGNISIGN_BANK_ID                  = "IGNISIGN_BANK_ID",
}

export enum IGNISIGN_BROADCASTABLE_ACTIONS {
  AUTH_METHOD_REFS        = 'AUTH_METHOD_REFS',
  NEED_PRIVATE_FILE_URL   = 'NEED_PRIVATE_FILE_URL',
  OPEN_URL                = 'OPEN_URL',
  SIGNATURE_FINALIZED     = 'SIGNATURE_FINALIZED',
  SIGNATURE_ERROR         = 'SIGNATURE_ERROR',
}

export type IGNISIGN_BROADCASTABLE_ACTIONS_TYPE = 
  IGNISIGN_BROADCASTABLE_ACTIONS_AUTH_METHOD_REFS    |
  IGNISIGN_BROADCASTABLE_ACTIONS_NEED_PRIVATE_FILE   |
  IGNISIGN_BROADCASTABLE_ACTIONS_OPEN_URL            |
  IGNISIGN_BROADCASTABLE_ACTIONS_SIGNATURE_FINALIZED |
  IGNISIGN_BROADCASTABLE_ACTIONS_SIGNATURE_ERROR;


export type IGNISIGN_BROADCASTABLE_ACTIONS_AUTH_METHOD_REFS = {
  type: IGNISIGN_BROADCASTABLE_ACTIONS.AUTH_METHOD_REFS,
  data: {
    authInfos: {
      token: string,
      type: IGNISIGN_SINGLE_AUTH_METHOD_REF,
    }[]
  }
}

export type IGNISIGN_BROADCASTABLE_ACTIONS_NEED_PRIVATE_FILE = {
  type: IGNISIGN_BROADCASTABLE_ACTIONS.NEED_PRIVATE_FILE_URL,
  data: {
    documentId: string
    externalDocumentId?: string
  }
}

export type IGNISIGN_BROADCASTABLE_ACTIONS_OPEN_URL = {
  type: IGNISIGN_BROADCASTABLE_ACTIONS.OPEN_URL,
  data: {
    url: string
  }
}

export type IGNISIGN_BROADCASTABLE_ACTIONS_SIGNATURE_FINALIZED = {
  type: IGNISIGN_BROADCASTABLE_ACTIONS.SIGNATURE_FINALIZED,
  data: {
    signatureIds: string[]
  }
}

export type IGNISIGN_BROADCASTABLE_ACTIONS_SIGNATURE_ERROR = {
  type: IGNISIGN_BROADCASTABLE_ACTIONS.SIGNATURE_ERROR,
  data: {
    errorCode     : IGNISIGN_ERROR_CODES;
    errorContext ?: any;
  }
}

export const IGNISIGN_BROADCASTABLE_SIMPLE_AUTH_METHOD_REFS: IGNISIGN_SINGLE_AUTH_METHOD_REF[] = [
  IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_PASS_KEY,
  IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_DAPP_WALLET,
  IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_PRIVATE_KEY_POSSESSION,
]

export enum IGNISIGN_AUTH_EXECUTION_MODE {
  SYNC = "SYNC",
  ASYNC = "ASYNC"
}

export enum IGNISIGN_AUTH_REGISTRATION_MODE {
  //AUTOMATIC = "AUTOMATIC",
  SYNC      = "SYNC",
  ASYNC     = "ASYNC"
}

export enum IGNISIGN_AUTH_FULL_MECHANISM_REF {
  SIMPLE                = 'SIMPLE',
  PHONE_SMS             = 'PHONE_SMS',
  PHONE_CALL            = 'PHONE_CALL',
  TOTP                  = "TOTP",
  PASS_KEY_POSSESSION   = 'PASS_KEY_POSSESSION',
  EID                   = 'EID',
}


export enum IGNISIGN_AUTH_REGISTRATION_STATUS {
  CREATED                         = "CREATED",
  IN_PROGRESS                     = "IN_PROGRESS",
  WAITING_VALIDATION              = "WAITING_VALIDATION",
  COMPLETED                       = "COMPLETED",
  CANCELLED                       = "CANCELLED",
  FAILED                          = "FAILED",
}

export enum IGNISIGN_AUTH_REGISTRATION_REF {
   IGNISIGN_SMS_NONCE               = "IGNISIGN_SMS_NONCE",
   APP_KNOWLEDGE                    = "APP_KNOWLEDGE",
   IGNISIGN_PASS_KEY                = "IGNISIGN_PASS_KEY",
   IGNISIGN_PRIVATE_KEY_POSSESSION  = "IGNISIGN_PRIVATE_KEY_POSSESSION",
   IGNISIGN_DAPP_WALLET             = "IGNISIGN_DAPP_WALLET",
   IGNISIGN_TOTP                    = "IGNISIGN_TOTP",
   IGNISIGN_EMAIL_TOKEN             = "IGNISIGN_EMAIL_TOKEN",
}

export const IgnisignAuthFullMechanismRef_To_IgnisignAuthRegistrationRef: {[key in IGNISIGN_AUTH_FULL_MECHANISM_REF] ?: IGNISIGN_AUTH_REGISTRATION_REF} = {
  [IGNISIGN_AUTH_FULL_MECHANISM_REF.PHONE_SMS]             : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_SMS_NONCE,
  // [IGNISIGN_AUTH_FULL_MECHANISM_REF.PHONE_CALL]            : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_CALL_NONCE,
  [IGNISIGN_AUTH_FULL_MECHANISM_REF.TOTP]                  : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_TOTP,
  [IGNISIGN_AUTH_FULL_MECHANISM_REF.PASS_KEY_POSSESSION]   : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_PASS_KEY,
  // [IGNISIGN_AUTH_FULL_MECHANISM_REF.EID]                   : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_EID,
};

export const IgnisignSingleAuthMethodmRef_To_IgnisignAuthRegistrationRef: {[key in IGNISIGN_SINGLE_AUTH_METHOD_REF] ?: IGNISIGN_AUTH_REGISTRATION_REF} = {
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_SMS_NONCE]               : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_SMS_NONCE,
  // [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_CALL_NONCE]              : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_CALL_NONCE,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_TOTP]                     : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_TOTP,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_PASS_KEY]                 : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_PASS_KEY,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_PRIVATE_KEY_POSSESSION]   : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_PRIVATE_KEY_POSSESSION,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_DAPP_WALLET]              : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_DAPP_WALLET,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_EMAIL_TOKEN]              : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_EMAIL_TOKEN,
  [IGNISIGN_SINGLE_AUTH_METHOD_REF.APP_KNOWLEDGE]                     : IGNISIGN_AUTH_REGISTRATION_REF.APP_KNOWLEDGE,
  // [IGNISIGN_SINGLE_AUTH_METHOD_REF.IGNISIGN_EID]                      : IGNISIGN_AUTH_REGISTRATION_REF.IGNISIGN_EID,
};