/**
 * Countries Public Model
 * 
 * Provides standardized country code handling using ISO 3166-1 alpha-2 codes. Implements both an enum 
 * for type safety and a detailed list with country names for display purposes, covering all recognized 
 * sovereign states and territories.
 * 
 * Key Points:
 * - Uses ISO 3166-1 alpha-2 two-letter codes for standardization
 * - Includes 249 countries and territories for comprehensive coverage
 * - Provides both enum (COUNTRIES) for type safety and detailed list (COUNTRY_LIST) for display
 * - Maintains official country names in English
 * 
 * Integration Points:
 * - Used in address validation for user profiles and documents
 * - Referenced in document localization for regional compliance
 * - Used for signer nationality tracking in KYC processes
 * - Applied in compliance verification for regulated operations
 * 
 * Dependencies:
 * - No external dependencies required
 * - Used by various modules requiring country information
 * 
 * Gotchas:
 * - All country codes are uppercase (differs from some standards using lowercase)
 * - Includes territories that may not be universally recognized (e.g., 'XK' for Kosovo)
 * - Some countries have multiple names/codes in different systems
 * - Must match exactly when comparing codes (case-sensitive)
 * - List order is alphabetical by country code, not by name
 */

export enum COUNTRIES {
  AW = 'AW', AF = 'AF', AO = 'AO', AI = 'AI', AL = 'AL', AD = 'AD', AE = 'AE', AR = 'AR', AM = 'AM', AS = 'AS', AG = 'AG', AU = 'AU', AT = 'AT',
  AZ = 'AZ', BI = 'BI', BE = 'BE', BJ = 'BJ', BF = 'BF', BD = 'BD', BG = 'BG', BH = 'BH', BS = 'BS', BA = 'BA', BL = 'BL', BY = 'BY', BZ = 'BZ',
  BM = 'BM', BO = 'BO', BR = 'BR', BB = 'BB', BN = 'BN', BT = 'BT', BW = 'BW', CF = 'CF', CA = 'CA', CH = 'CH', CL = 'CL', CN = 'CN', CI = 'CI',
  CM = 'CM', CD = 'CD', CG = 'CG', CK = 'CK', CO = 'CO', KM = 'KM', CV = 'CV', CR = 'CR', CU = 'CU', CW = 'CW', KY = 'KY', CY = 'CY', CZ = 'CZ',
  DE = 'DE', DJ = 'DJ', DM = 'DM', DK = 'DK', DO = 'DO', DZ = 'DZ', EC = 'EC', EG = 'EG', ER = 'ER', EH = 'EH', ES = 'ES', EE = 'EE', ET = 'ET',
  FI = 'FI', FJ = 'FJ', FK = 'FK', FR = 'FR', FO = 'FO', FM = 'FM', GA = 'GA', GB = 'GB', GE = 'GE', GG = 'GG', GH = 'GH', GI = 'GI', GN = 'GN',
  GM = 'GM', GW = 'GW', GQ = 'GQ', GR = 'GR', GD = 'GD', GL = 'GL', GT = 'GT', GU = 'GU', GY = 'GY', HK = 'HK', HN = 'HN', HR = 'HR', HT = 'HT',
  HU = 'HU', ID = 'ID', IM = 'IM', IN = 'IN', IE = 'IE', IR = 'IR', IQ = 'IQ', IS = 'IS', IL = 'IL', IT = 'IT', JM = 'JM', JE = 'JE', JO = 'JO',
  JP = 'JP', KZ = 'KZ', KE = 'KE', KG = 'KG', KH = 'KH', KN = 'KN', KR = 'KR', XK = 'XK', KW = 'KW', LA = 'LA', LB = 'LB', LR = 'LR', LY = 'LY',
  LC = 'LC', LI = 'LI', LK = 'LK', LS = 'LS', LT = 'LT', LU = 'LU', LV = 'LV', MO = 'MO', MF = 'MF', MA = 'MA', MC = 'MC', MD = 'MD', MG = 'MG',
  MV = 'MV', MX = 'MX', MK = 'MK', ML = 'ML', MT = 'MT', MM = 'MM', ME = 'ME', MN = 'MN', MZ = 'MZ', MR = 'MR', MU = 'MU', MW = 'MW', MY = 'MY',
  YT = 'YT', NA = 'NA', NC = 'NC', NE = 'NE', NF = 'NF', NG = 'NG', NI = 'NI', NL = 'NL', NO = 'NO', NP = 'NP', NR = 'NR', NZ = 'NZ', OM = 'OM',
  PK = 'PK', PA = 'PA', PE = 'PE', PH = 'PH', PG = 'PG', PL = 'PL', PR = 'PR', KP = 'KP', PT = 'PT', PY = 'PY', PS = 'PS', QA = 'QA', RE = 'RE',
  RO = 'RO', RU = 'RU', RW = 'RW', SA = 'SA', SD = 'SD', SN = 'SN', SG = 'SG', GS = 'GS', SL = 'SL', SV = 'SV', SM = 'SM', SO = 'SO', RS = 'RS',
  SS = 'SS', ST = 'ST', SR = 'SR', SK = 'SK', SI = 'SI', SE = 'SE', SZ = 'SZ', SX = 'SX', SC = 'SC', SY = 'SY', TD = 'TD', TG = 'TG', TH = 'TH',
  TJ = 'TJ', TM = 'TM', TL = 'TL', TO = 'TO', TT = 'TT', TN = 'TN', TR = 'TR', TV = 'TV', TW = 'TW', TZ = 'TZ', UG = 'UG', UA = 'UA', UY = 'UY',
  US = 'US', UZ = 'UZ', VA = 'VA', VE = 'VE', VG = 'VG', VI = 'VI', VN = 'VN', VU = 'VU', WF = 'WF', WS = 'WS', YE = 'YE', ZA = 'ZA', ZM = 'ZM',
  ZW = 'ZW'
};

export const COUNTRY_LIST = [
  { code : 'AF', name: 'Afghanistan'},
  { code : 'AW', name : 'Aruba' },
  { code : 'AO', name : 'Angola' },
  { code : 'AI', name : 'Anguilla' },
  { code : 'AL', name : 'Albania' },
  { code : 'AD', name : 'Andorra' },
  { code : 'AE', name : 'United Arab Emirates' },
  { code : 'AR', name : 'Argentina' },
  { code : 'AM', name : 'Armenia' },
  { code : 'AS', name : 'American Samoa' },
  { code : 'AG', name : 'Antigua and Barbuda' },
  { code : 'AU', name : 'Australia' },
  { code : 'AT', name : 'Austria' },
  { code : 'AZ', name : 'Azerbaijan' },
  { code : 'BI', name : 'Burundi' },
  { code : 'BE', name : 'Belgium' },
  { code : 'BJ', name : 'Benin' },
  { code : 'BF', name : 'Burkina Faso' },
  { code : 'BD', name : 'Bangladesh' },
  { code : 'BG', name : 'Bulgaria' },
  { code : 'BH', name : 'Bahrain' },
  { code : 'BS', name : 'Bahamas' },
  { code : 'BA', name : 'Bosnia and Herzegovina' },
  { code : 'BL', name : 'Saint Barthélemy' },
  { code : 'BY', name : 'Belarus' },
  { code : 'BZ', name : 'Belize' },
  { code : 'BM', name : 'Bermuda' },
  { code : 'BO', name : 'Bolivia' },
  { code : 'BR', name : 'Brazil' },
  { code : 'BB', name : 'Barbados' },
  { code : 'BN', name : 'Brunei' },
  { code : 'BT', name : 'Bhutan' },
  { code : 'BW', name : 'Botswana' },
  { code : 'CF', name : 'Central African Republic' },
  { code : 'CA', name : 'Canada' },
  { code : 'CH', name : 'Switzerland' },
  { code : 'CL', name : 'Chile' },
  { code : 'CN', name : 'China' },
  { code : 'CI', name : 'Ivory Coast' },
  { code : 'CM', name : 'Cameroon' },
  { code : 'CD', name : 'DR Congo' },
  { code : 'CG', name : 'Republic of the Congo' },
  { code : 'CK', name : 'Cook Islands' },
  { code : 'CO', name : 'Colombia' },
  { code : 'KM', name : 'Comoros' },
  { code : 'CV', name : 'Cape Verde' },
  { code : 'CR', name : 'Costa Rica' },
  { code : 'CU', name : 'Cuba' },
  { code : 'CW', name : 'Curaçao' },
  { code : 'KY', name : 'Cayman Islands' },
  { code : 'CY', name : 'Cyprus' },
  { code : 'CZ', name : 'Czechia' },
  { code : 'DE', name : 'Germany' },
  { code : 'DJ', name : 'Djibouti' },
  { code : 'DM', name : 'Dominica' },
  { code : 'DK', name : 'Denmark' },
  { code : 'DO', name : 'Dominican Republic' },
  { code : 'DZ', name : 'Algeria' },
  { code : 'EC', name : 'Ecuador' },
  { code : 'EG', name : 'Egypt' },
  { code : 'ER', name : 'Eritrea' },
  { code : 'EH', name : 'Western Sahara' },
  { code : 'ES', name : 'Spain' },
  { code : 'EE', name : 'Estonia' },
  { code : 'ET', name : 'Ethiopia' },
  { code : 'FI', name : 'Finland' },
  { code : 'FJ', name : 'Fiji' },
  { code : 'FK', name : 'Falkland Islands' },
  { code : 'FR', name : 'France' },
  { code : 'FO', name : 'Faroe Islands' },
  { code : 'FM', name : 'Micronesia' },
  { code : 'GA', name : 'Gabon' },
  { code : 'GB', name : 'United Kingdom' },
  { code : 'GE', name : 'Georgia' },
  { code : 'GG', name : 'Guernsey' },
  { code : 'GH', name : 'Ghana' },
  { code : 'GI', name : 'Gibraltar' },
  { code : 'GN', name : 'Guinea' },
  { code : 'GM', name : 'Gambia' },
  { code : 'GW', name : 'Guinea-Bissau' },
  { code : 'GQ', name : 'Equatorial Guinea' },
  { code : 'GR', name : 'Greece' },
  { code : 'GD', name : 'Grenada' },
  { code : 'GL', name : 'Greenland' },
  { code : 'GT', name : 'Guatemala' },
  { code : 'GU', name : 'Guam' },
  { code : 'GY', name : 'Guyana' },
  { code : 'HK', name : 'Hong Kong' },
  { code : 'HN', name : 'Honduras' },
  { code : 'HR', name : 'Croatia' },
  { code : 'HT', name : 'Haiti' },
  { code : 'HU', name : 'Hungary' },
  { code : 'ID', name : 'Indonesia' },
  { code : 'IM', name : 'Isle of Man' },
  { code : 'IN', name : 'India' },
  { code : 'IE', name : 'Ireland' },
  { code : 'IR', name : 'Iran' },
  { code : 'IQ', name : 'Iraq' },
  { code : 'IS', name : 'Iceland' },
  { code : 'IL', name : 'Israel' },
  { code : 'IT', name : 'Italy' },
  { code : 'JM', name : 'Jamaica' },
  { code : 'JE', name : 'Jersey' },
  { code : 'JO', name : 'Jordan' },
  { code : 'JP', name : 'Japan' },
  { code : 'KZ', name : 'Kazakhstan' },
  { code : 'KE', name : 'Kenya' },
  { code : 'KG', name : 'Kyrgyzstan' },
  { code : 'KH', name : 'Cambodia' },
  { code : 'KN', name : 'Saint Kitts and Nevis' },
  { code : 'KR', name : 'South Korea' },
  { code : 'XK', name : 'Kosovo' },
  { code : 'KW', name : 'Kuwait' },
  { code : 'LA', name : 'Laos' },
  { code : 'LB', name : 'Lebanon' },
  { code : 'LR', name : 'Liberia' },
  { code : 'LY', name : 'Libya' },
  { code : 'LC', name : 'Saint Lucia' },
  { code : 'LI', name : 'Liechtenstein' },
  { code : 'LK', name : 'Sri Lanka' },
  { code : 'LS', name : 'Lesotho' },
  { code : 'LT', name : 'Lithuania' },
  { code : 'LU', name : 'Luxembourg' },
  { code : 'LV', name : 'Latvia' },
  { code : 'MO', name : 'Macau' },
  { code : 'MF', name : 'Saint Martin' },
  { code : 'MA', name : 'Morocco' },
  { code : 'MC', name : 'Monaco' },
  { code : 'MD', name : 'Moldova' },
  { code : 'MG', name : 'Madagascar' },
  { code : 'MV', name : 'Maldives' },
  { code : 'MX', name : 'Mexico' },
  { code : 'MK', name : 'Macedonia' },
  { code : 'ML', name : 'Mali' },
  { code : 'MT', name : 'Malta' },
  { code : 'MM', name : 'Myanmar' },
  { code : 'ME', name : 'Montenegro' },
  { code : 'MN', name : 'Mongolia' },
  { code : 'MZ', name : 'Mozambique' },
  { code : 'MR', name : 'Mauritania' },
  { code : 'MU', name : 'Mauritius' },
  { code : 'MW', name : 'Malawi' },
  { code : 'MY', name : 'Malaysia' },
  { code : 'YT', name : 'Mayotte' },
  { code : 'NA', name : 'Namibia' },
  { code : 'NC', name : 'New Caledonia' },
  { code : 'NE', name : 'Niger' },
  { code : 'NF', name : 'Norfolk Island' },
  { code : 'NG', name : 'Nigeria' },
  { code : 'NI', name : 'Nicaragua' },
  { code : 'NL', name : 'Netherlands' },
  { code : 'NO', name : 'Norway' },
  { code : 'NP', name : 'Nepal' },
  { code : 'NR', name : 'Nauru' },
  { code : 'NZ', name : 'New Zealand' },
  { code : 'OM', name : 'Oman' },
  { code : 'PK', name : 'Pakistan' },
  { code : 'PA', name : 'Panama' },
  { code : 'PE', name : 'Peru' },
  { code : 'PH', name : 'Philippines' },
  { code : 'PG', name : 'Papua New Guinea' },
  { code : 'PL', name : 'Poland' },
  { code : 'PR', name : 'Puerto Rico' },
  { code : 'KP', name : 'North Korea' },
  { code : 'PT', name : 'Portugal' },
  { code : 'PY', name : 'Paraguay' },
  { code : 'PS', name : 'Palestine' },
  { code : 'QA', name : 'Qatar' },
  { code : 'RE', name : 'Réunion' },
  { code : 'RO', name : 'Romania' },
  { code : 'RU', name : 'Russia' },
  { code : 'RW', name : 'Rwanda' },
  { code : 'SA', name : 'Saudi Arabia' },
  { code : 'SD', name : 'Sudan' },
  { code : 'SN', name : 'Senegal' },
  { code : 'SG', name : 'Singapore' },
  { code : 'GS', name : 'South Georgia' },
  { code : 'SL', name : 'Sierra Leone' },
  { code : 'SV', name : 'El Salvador' },
  { code : 'SM', name : 'San Marino' },
  { code : 'SO', name : 'Somalia' },
  { code : 'RS', name : 'Serbia' },
  { code : 'SS', name : 'South Sudan' },
  { code : 'ST', name : 'São Tomé and Príncipe' },
  { code : 'SR', name : 'Suriname' },
  { code : 'SK', name : 'Slovakia' },
  { code : 'SI', name : 'Slovenia' },
  { code : 'SE', name : 'Sweden' },
  { code : 'SZ', name : 'Swaziland' },
  { code : 'SX', name : 'Sint Maarten' },
  { code : 'SC', name : 'Seychelles' },
  { code : 'SY', name : 'Syria' },
  { code : 'TD', name : 'Chad' },
  { code : 'TG', name : 'Togo' },
  { code : 'TH', name : 'Thailand' },
  { code : 'TJ', name : 'Tajikistan' },
  { code : 'TM', name : 'Turkmenistan' },
  { code : 'TL', name : 'Timor-Leste' },
  { code : 'TO', name : 'Tonga' },
  { code : 'TT', name : 'Trinidad and Tobago' },
  { code : 'TN', name : 'Tunisia' },
  { code : 'TR', name : 'Turkey' },
  { code : 'TV', name : 'Tuvalu' },
  { code : 'TW', name : 'Taiwan' },
  { code : 'TZ', name : 'Tanzania' },
  { code : 'UG', name : 'Uganda' },
  { code : 'UA', name : 'Ukraine' },
  { code : 'UY', name : 'Uruguay' },
  { code : 'US', name : 'United States' },
  { code : 'UZ', name : 'Uzbekistan' },
  { code : 'VA', name : 'Vatican City' },
  { code : 'VE', name : 'Venezuela' },
  { code : 'VG', name : 'British Virgin Islands' },
  { code : 'VI', name : 'United States Virgin Islands' },
  { code : 'VN', name : 'Vietnam' },
  { code : 'VU', name : 'Vanuatu' },
  { code : 'WF', name : 'Wallis and Futuna' },
  { code : 'WS', name : 'Samoa' },
  { code : 'YE', name : 'Yemen' },
  { code : 'ZA', name : 'South Africa' },
  { code : 'ZM', name : 'Zambia' },
  { code : 'ZW', name : 'Zimbabwe' }
];