export enum IGNISIGN_SIGNATURE_LANGUAGES {
  EN = "EN",
  FR = "FR",
  DE = "DE"
}

export enum IGNISIGN_DIRECTION_OF_LANGUAGE {
  LTR = "ltr",
  RTL = "rtl"
}

export const IGNISIGN_LANGUAGES_DIRECTION = {
  [IGNISIGN_SIGNATURE_LANGUAGES.EN] : IGNISIGN_DIRECTION_OF_LANGUAGE.LTR,
  [IGNISIGN_SIGNATURE_LANGUAGES.FR] : IGNISIGN_DIRECTION_OF_LANGUAGE.LTR,
  [IGNISIGN_SIGNATURE_LANGUAGES.DE] : IGNISIGN_DIRECTION_OF_LANGUAGE.LTR
}

export const DEFAULT_SIGNATURE_LANGUAGE = IGNISIGN_SIGNATURE_LANGUAGES.EN;