export enum IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL {
  BASIC     = "BASIC",
  ADVANCED  = "ADVANCED",
  CRITICAL  = "CRITICAL",
}

export enum IGNISIGN_IAM_FUNCTIONS {
  PLATFORM_MANAGEMENT          = 'PLATFORM_MANAGEMENT',
  ORG_ARCHIVING                = 'ORG_ARCHIVING',             
  BILLING                      = 'BILLING',
  ORG_MEMBER_MANAGEMENT        = 'ORG_MEMBER_MANAGEMENT',
  DELEGATION_AGREEMENT         = 'DELEGATION_AGREEMENT',
  ORG_BASIC_INFORMATION        = 'ORG_BASIC_INFORMATION',
  APP_CUSTOMIZATION            = 'APP_CUSTOMIZATION',
  APP_MEMBERS_MANAGEMENT       = 'APP_MEMBERS_MANAGEMENT',
  API_KEYS                     = 'API_KEYS',
  WEBHOOKS                     = 'WEBHOOKS',                     
  DOC_TEMPLATE                 = 'DOC_TEMPLATE',                 
  SIGNATURE_PROFILE            = 'SIGNATURE_PROFILE',            
  SIGNATURE_REQUEST            = 'SIGNATURE_REQUEST',            
  SIGNERS                      = 'SIGNERS',                      
  SIGNATURE_SESSION            = 'SIGNATURE_SESSION',            
  SIGNATURE_PROOF_RESTRICTED   = 'SIGNATURE_PROOF_RESTRICTED',   
  SIGNATURE_PROOF_SHARED       = 'SIGNATURE_PROOF_SHARED',       
  PROVIDE_DOCUMENT_INVITED     = 'PROVIDE_DOCUMENT_INVITED',      
}

export enum IGNISIGN_IAM_SCOPES {
  PLATFORM          = 'PLATFORM',
  ORGANIZATION      = 'ORGANIZATION',
  APPLICATION       = 'APPLICATION',
  APPLICATION_ENV   = 'APPLICATION_ENV',
  SIGNATURE_PROFILE = 'SIGNATURE_PROFILE',
  SIGNATURE_REQUEST = 'SIGNATURE_REQUEST',
  SIGNATURE_SESSION = 'SIGNATURE_SESSION',
}


export enum IGNISIGN_IAM_RIGHTS {
  READ     = 'READ',
  WRITE    = 'WRITE',
  GENERATE = 'GENERATE',
  EXECUTE  = 'EXECUTE',
  ARCHIVE  = 'ARCHIVE',
  DELETE   = 'DELETE',
  PROVIDE  = 'PROVIDE',
  INIT     = 'INIT',
}

export enum IGNISIGN_IAM_PERMISSIONS {
  PLATFORM_KPI                     = "PLATFORM_KPI",
  PLATFORM_ORGANIZATION_MANAGEMENT = "PLATFORM_ORGANIZATION_MANAGEMENT",
  PLATFORM_USER_MANAGEMENT         = "PLATFORM_APPLICATION_MANAGEMENT",
  ORG_ARCHIVING                    = "ORG_ARCHIVING", 
  ORG_BILLING                      = "ORG_BILLING", 
  ORG_MEMBER_MANAGEMENT            = "ORG_MEMBER_MANAGEMENT", 
  ORG_DELEGATION_AGREEMENT         = "ORG_DELEGATION_AGREEMENT", 
  ORG_BASICINFORMATION_READ        = "ORG_BASICINFORMATION_READ", 
  ORG_BASICINFORMATION_WRITE       = "ORG_BASICINFORMATION_WRITE", 
  APP_CUSTOMIZATION                = "APP_CUSTOMIZATION", 
  APP_MEMBER_MANAGEMENT            = "APP_MEMBER_MANAGEMENT", 
  API_KEYS_MANAGEMENT              = "API_KEYS_MANAGEMENT", 
  WEBHOOKS_MANAGEMENT              = "WEBHOOKS_MANAGEMENT", 
  DOC_TEMPLATE_MANAGEMENT          = "DOC_TEMPLATE_MANAGEMENT", 
  DOC_TEMPLATE_READ                = "DOC_TEMPLATE_READ", 
  SIGNATURE_PROFILE_MANAGEMENT     = "SIGNATURE_PROFILE_MANAGEMENT", 
  SIGNATURE_PROFILE_READ           = "SIGNATURE_PROFILE_READ", 
  SIGNATURE_REQUEST_MANAGEMENT     = "SIGNATURE_REQUEST_MANAGEMENT", 
  SIGNATURE_REQUEST_READ           = "SIGNATURE_REQUEST_READ", 
  SIGNERS_MANAGEMENT               = "SIGNERS_MANAGEMENT", 
  SIGNERS_READ                     = "SIGNERS_READ", 
  SIGNATURE_SESSION_EXECUTION      = "SIGNATURE_SESSION_EXECUTION", 
  SIGNATURE_PROOF_RESTRICTED_READ  = "SIGNATURE_PROOF_RESTRICTED_READ", 
  SIGNATURE_PROOF_SHARED_READ      = "SIGNATURE_PROOF_SHARED_READ", 
  DOCUMENT_PROVIDER                = "DOCUMENT_PROVIDER", 
}

export enum IGNISIGN_IAM_ROLE {
  INTERNAL_API              = 'INTERNAL_API',
  SUPER_ADMIN               = 'SUPER_ADMIN',
  ORG_OWNER                 = 'ORG_OWNER',
  ORG_ADMIN                 = 'ORG_ADMIN',
  ORG_BILLING               = 'ORG_BILLING',
  ORG_USER                  = 'ORG_USER',
  APP_ADMIN                 = 'APP_ADMIN',
  APP_MANAGER               = 'APP_MANAGER',
  APP_OPERATOR              = 'APP_OPERATOR',
  APP_READER                = 'APP_READER',
  SIGNERS                   = 'SIGNERS',
  INVITED_PROOF_READER      = 'INVITED_PROOF_READER',
  INVITED_DOCUMENT_PROVIDER = 'INVITED_PROOF_PROVIDER',
}


export const IgnisignIam_FunctionScopeMapping : {[keys in IGNISIGN_IAM_FUNCTIONS] : IGNISIGN_IAM_SCOPES }= {
  [IGNISIGN_IAM_FUNCTIONS.PLATFORM_MANAGEMENT]         : IGNISIGN_IAM_SCOPES.PLATFORM,
  [IGNISIGN_IAM_FUNCTIONS.ORG_ARCHIVING]               : IGNISIGN_IAM_SCOPES.ORGANIZATION,
  [IGNISIGN_IAM_FUNCTIONS.BILLING]                     : IGNISIGN_IAM_SCOPES.ORGANIZATION,
  [IGNISIGN_IAM_FUNCTIONS.ORG_MEMBER_MANAGEMENT]       : IGNISIGN_IAM_SCOPES.ORGANIZATION,
  [IGNISIGN_IAM_FUNCTIONS.DELEGATION_AGREEMENT]        : IGNISIGN_IAM_SCOPES.ORGANIZATION,
  [IGNISIGN_IAM_FUNCTIONS.ORG_BASIC_INFORMATION]       : IGNISIGN_IAM_SCOPES.ORGANIZATION,
  [IGNISIGN_IAM_FUNCTIONS.APP_CUSTOMIZATION]           : IGNISIGN_IAM_SCOPES.APPLICATION,
  [IGNISIGN_IAM_FUNCTIONS.APP_MEMBERS_MANAGEMENT]      : IGNISIGN_IAM_SCOPES.APPLICATION,
  [IGNISIGN_IAM_FUNCTIONS.API_KEYS]                    : IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
  [IGNISIGN_IAM_FUNCTIONS.WEBHOOKS]                    : IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
  [IGNISIGN_IAM_FUNCTIONS.DOC_TEMPLATE]                : IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
  [IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROFILE]           : IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
  [IGNISIGN_IAM_FUNCTIONS.SIGNATURE_REQUEST]           : IGNISIGN_IAM_SCOPES.SIGNATURE_PROFILE,
  [IGNISIGN_IAM_FUNCTIONS.SIGNERS]                     : IGNISIGN_IAM_SCOPES.SIGNATURE_PROFILE,
  [IGNISIGN_IAM_FUNCTIONS.SIGNATURE_SESSION]           : IGNISIGN_IAM_SCOPES.SIGNATURE_PROFILE,
  [IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROOF_RESTRICTED]  : IGNISIGN_IAM_SCOPES.SIGNATURE_REQUEST,
  [IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROOF_SHARED]      : IGNISIGN_IAM_SCOPES.SIGNATURE_REQUEST,
  [IGNISIGN_IAM_FUNCTIONS.PROVIDE_DOCUMENT_INVITED]    : IGNISIGN_IAM_SCOPES.SIGNATURE_REQUEST,
}


export const IgnisignIam_PermissionsDef : {[keys in IGNISIGN_IAM_PERMISSIONS] : { function: IGNISIGN_IAM_FUNCTIONS, rights: IGNISIGN_IAM_RIGHTS[], orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL } }= {
  [IGNISIGN_IAM_PERMISSIONS.PLATFORM_ORGANIZATION_MANAGEMENT] : { 
    function: IGNISIGN_IAM_FUNCTIONS.PLATFORM_MANAGEMENT,        
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ], 
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL 
  },

  [IGNISIGN_IAM_PERMISSIONS.PLATFORM_USER_MANAGEMENT]         : { 
    function: IGNISIGN_IAM_FUNCTIONS.PLATFORM_MANAGEMENT,        
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ], 
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },

  [IGNISIGN_IAM_PERMISSIONS.PLATFORM_KPI]                     : { 
    function: IGNISIGN_IAM_FUNCTIONS.PLATFORM_MANAGEMENT,        
    rights: [IGNISIGN_IAM_RIGHTS.READ],
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.ORG_ARCHIVING]                    : { 
    function: IGNISIGN_IAM_FUNCTIONS.ORG_ARCHIVING,              
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },

  [IGNISIGN_IAM_PERMISSIONS.ORG_BILLING]                      : { 
    function: IGNISIGN_IAM_FUNCTIONS.BILLING,                    
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.ORG_MEMBER_MANAGEMENT]            : { 
    function: IGNISIGN_IAM_FUNCTIONS.ORG_MEMBER_MANAGEMENT,      
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.ORG_DELEGATION_AGREEMENT]         : { 
    function: IGNISIGN_IAM_FUNCTIONS.DELEGATION_AGREEMENT,       
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_READ]        : { 
    function: IGNISIGN_IAM_FUNCTIONS.ORG_BASIC_INFORMATION,      
    rights: [IGNISIGN_IAM_RIGHTS.READ ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.BASIC
  },
  [IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_WRITE]       : { 
    function: IGNISIGN_IAM_FUNCTIONS.ORG_BASIC_INFORMATION,      
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION]                : { 
    function: IGNISIGN_IAM_FUNCTIONS.APP_CUSTOMIZATION,          
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT]            : { 
    function: IGNISIGN_IAM_FUNCTIONS.APP_MEMBERS_MANAGEMENT,     
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT]              : { 
    function: IGNISIGN_IAM_FUNCTIONS.API_KEYS,                   
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.GENERATE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT]              : { 
    function: IGNISIGN_IAM_FUNCTIONS.WEBHOOKS,                   
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT]          : { 
    function: IGNISIGN_IAM_FUNCTIONS.DOC_TEMPLATE,               
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_READ]                : { 
    function: IGNISIGN_IAM_FUNCTIONS.DOC_TEMPLATE,               
    rights: [IGNISIGN_IAM_RIGHTS.READ ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.BASIC}
    ,
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT]     : 
  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROFILE,          
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_READ]           : { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROFILE,          
    rights: [IGNISIGN_IAM_RIGHTS.READ ],
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT]     : 

  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_REQUEST,          
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.WRITE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_READ]           : { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_REQUEST,          
    rights: [IGNISIGN_IAM_RIGHTS.READ ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT]               : 
  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNERS,                    
    rights: [IGNISIGN_IAM_RIGHTS.READ, IGNISIGN_IAM_RIGHTS.INIT ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNERS_READ]                     : { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNERS,                    
    rights: [IGNISIGN_IAM_RIGHTS.READ ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_SESSION_EXECUTION]      : 
  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_SESSION,     // ?? hors scope ?      
    rights: [IGNISIGN_IAM_RIGHTS.EXECUTE ] ,
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.CRITICAL
  },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ]  : 
  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROOF_RESTRICTED, 
    rights: [IGNISIGN_IAM_RIGHTS.READ ],
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.ADVANCED },
  [IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ]      : 
    
  { 
    function: IGNISIGN_IAM_FUNCTIONS.SIGNATURE_PROOF_SHARED,     
    rights: [IGNISIGN_IAM_RIGHTS.READ ],
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.BASIC },
  [IGNISIGN_IAM_PERMISSIONS.DOCUMENT_PROVIDER]                :  
  { 
    function: IGNISIGN_IAM_FUNCTIONS.PROVIDE_DOCUMENT_INVITED,   
    rights: [IGNISIGN_IAM_RIGHTS.PROVIDE ], 
    orgAuthAccreditationLevel : IGNISIGN_AUTH_ORGANIZATION_ACCREDITATION_LEVEL.BASIC
  },
}


export const IgnisignIam_Policies : {[keys : string] : { scope: IGNISIGN_IAM_SCOPES, permissions: IGNISIGN_IAM_PERMISSIONS[] } } = {
  [ IGNISIGN_IAM_ROLE.INTERNAL_API ] : { 
    scope: IGNISIGN_IAM_SCOPES.PLATFORM,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_ORGANIZATION_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_USER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_KPI,
      IGNISIGN_IAM_PERMISSIONS.ORG_ARCHIVING,
      IGNISIGN_IAM_PERMISSIONS.ORG_BILLING,
      IGNISIGN_IAM_PERMISSIONS.ORG_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_DELEGATION_AGREEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_WRITE,
      IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION,
      IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,

    ]},
  [ IGNISIGN_IAM_ROLE.SUPER_ADMIN ]  : { 
    scope:  IGNISIGN_IAM_SCOPES.PLATFORM,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_ORGANIZATION_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_USER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.PLATFORM_KPI,
      IGNISIGN_IAM_PERMISSIONS.ORG_ARCHIVING,
      IGNISIGN_IAM_PERMISSIONS.ORG_BILLING,
      IGNISIGN_IAM_PERMISSIONS.ORG_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_DELEGATION_AGREEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_WRITE,
      IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION,
      IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ]},
  [ IGNISIGN_IAM_ROLE.ORG_OWNER ] : { 
    scope:  IGNISIGN_IAM_SCOPES.ORGANIZATION,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.ORG_ARCHIVING,
      IGNISIGN_IAM_PERMISSIONS.ORG_BILLING,
      IGNISIGN_IAM_PERMISSIONS.ORG_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_DELEGATION_AGREEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_WRITE,
      IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION,
      IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
    ]},
  [ IGNISIGN_IAM_ROLE.ORG_ADMIN ] : { 
    scope:  IGNISIGN_IAM_SCOPES.ORGANIZATION,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.ORG_ARCHIVING,
      IGNISIGN_IAM_PERMISSIONS.ORG_BILLING,
      IGNISIGN_IAM_PERMISSIONS.ORG_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_DELEGATION_AGREEMENT,
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_WRITE,
      IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION,
      IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.ORG_BILLING ]   : { 
    scope:  IGNISIGN_IAM_SCOPES.ORGANIZATION,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.ORG_BILLING,
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.ORG_USER ]      : { 
    scope:  IGNISIGN_IAM_SCOPES.ORGANIZATION,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.ORG_BASICINFORMATION_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.APP_ADMIN ]     : { 
    scope:  IGNISIGN_IAM_SCOPES.APPLICATION,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.APP_CUSTOMIZATION,
      IGNISIGN_IAM_PERMISSIONS.APP_MEMBER_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.API_KEYS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.APP_MANAGER ] : { 
    scope:  IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.WEBHOOKS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.APP_OPERATOR ] : { 
    scope:  IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_MANAGEMENT,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.APP_READER ] : { 
    scope:  IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.DOC_TEMPLATE_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROFILE_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_REQUEST_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNERS_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_RESTRICTED_READ,
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.SIGNERS ]       : { 
    scope:  IGNISIGN_IAM_SCOPES.APPLICATION_ENV,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_SESSION_EXECUTION,
  ] },

  [ IGNISIGN_IAM_ROLE.INVITED_PROOF_READER ]      : { 
    scope:  IGNISIGN_IAM_SCOPES.SIGNATURE_REQUEST,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.SIGNATURE_PROOF_SHARED_READ,
  ] },

  [ IGNISIGN_IAM_ROLE.INVITED_DOCUMENT_PROVIDER ] : { 
    scope:  IGNISIGN_IAM_SCOPES.SIGNATURE_REQUEST,
    permissions: [
      IGNISIGN_IAM_PERMISSIONS.DOCUMENT_PROVIDER
  ] }

}